### ISSUE TITLE
Build data set

### ISSUE THREAD

**Issue by Yong-Q** [hspark1212/MOFreinforce#21]
Can you share your approach to building the dataset? For example, write json from a cif structure

**Comment by hspark1212** [comment]
@qoffee @Yong-Q Sorry for the late reply.

I've pushed the data preparation notebook file in this [commit](https://github.com/hspark1212/MOFreinforce/commit/b920084a29db9223482ddfeffd2e775b82f49e63). I must admit that the process of constructing the dataset for the generator, predictor, and reinforcement learning is quite complex. To help with this, I've shared the [Google Drive link](https://drive.google.com/file/d/1vbvga2r7ANbc-K06GAyWm4F_jZ6U3C6W/view?usp=sharing) containing the data we used.

Since the generator is already pretrained with this dataset, you won't need to train it again. However, if you want to run reinforcement learning with different properties, you can do so after training a new predictor to predict the desired properties.

**Comment by qoffee** [comment]
@hspark1212 thanks, I looked at the notebook, but it is still not obvious to me how to get the correct input in the format:
`[topo, mc, ol, num_conn, frags, selfies]` which are in your dataset. Is it possible to share a small snippet of how to get the necessary information from the input `.cif` file?

**Comment by hspark1212** [comment]
Hi @qoffee 

Unfortunately, converting a CIF file to the required input format presents several challenges:

The structure of the CIF file needs to be decomposed into topology and building blocks that are compatible with the PORMAKE building blocks, as these are represented by categorical variables.
The organic linkers within the CIF file must also be extracted and converted into SELFIES.
Due to these complexities, we decided to construct a new dataset for this work rather than relying on pre-existing databases like the CoRE MOF database.

As outlined in the paper, the dataset was created through the following procedures:

Topology: Sourced from the [RCSC](https://github.com/Sangwon91/PORMAKE/tree/main/pormake/database/topologies) database.
Metal Clusters: Extracted from the building blocks database within [pormake](https://github.com/Sangwon91/PORMAKE/tree/main/pormake/database/bbs), including metals.
Organic Linkers: Taken from the building blocks database in [pormake](https://github.com/Sangwon91/PORMAKE/tree/main/pormake/database/bbs), excluding metals, and supplemented with merged building blocks for data augmentation.
This makes training reinforcement learning models on structures outside of the dataset used quite tricky.

Thanks,

**Comment by Yong-Q** [comment]
The database may not be the most important. What is needed is the process from a cif to its feature extraction. topo+ Node.cif can be obtained through pormake, and other features such as smile format conversion will be more important, as well as the digitization of topo/node
